# Generated by Django 3.1.1 on 2020-10-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arb_inst', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ArbsNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_arbs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_proc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_ammount', models.FloatField()),
                ('arbitral_institution', models.ManyToManyField(to='calc.ArbInst')),
                ('number_of_arbitrators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.arbsnum')),
                ('type_of_procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.typeproc')),
            ],
        ),
    ]
