# Generated by Django 3.1.1 on 2020-10-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='dispute_ammount',
            new_name='ammount_in_dispute',
        ),
    ]
