# Generated by Django 3.1.1 on 2020-11-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201028_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fee', models.FloatField(blank=True)),
                ('arb_fee', models.FloatField(blank=True)),
                ('arbs_fee', models.FloatField(blank=True)),
                ('admin_fee', models.FloatField(blank=True)),
                ('comment0', models.TextField(blank=True)),
                ('comment1', models.TextField(blank=True)),
                ('comment2', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='arbitral_institution',
            new_name='ai',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='ammount_in_dispute',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='number_of_arbitrators',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='type_of_procedure',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='arbs',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (5, '5'), (7, '7')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='proc',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Expedited', 'Expedited')], default='Standard', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arbinst',
            name='arb_inst',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='ArbsNum',
        ),
        migrations.DeleteModel(
            name='TypeProc',
        ),
        migrations.AddField(
            model_name='cost',
            name='ai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.arbinst'),
        ),
        migrations.AddField(
            model_name='cost',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.userrequest'),
        ),
    ]
