# Generated by Django 3.1.1 on 2020-11-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201102_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='admin_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='arb_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='arbs_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='comment0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='comment1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='comment2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='reg_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='arbs',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (7, '7')]),
        ),
    ]
