# Generated by Django 3.1.1 on 2020-11-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_auto_20201102_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='calc.userrequest'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='arbs',
            field=models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (7, '7')], default=3),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='proc',
            field=models.IntegerField(choices=[(1, 'Standard'), (2, 'Expedited')], default=1),
        ),
    ]
