# Generated by Django 3.1.1 on 2020-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20201103_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='arbs',
            field=models.IntegerField(choices=[(1, '1'), (3, '3')], default=3),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='proc',
            field=models.IntegerField(choices=[('Standard', 'Standard'), ('Standard', 'Expedited')], default='Standard'),
        ),
    ]
