# Generated by Django 3.1.1 on 2020-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20201108_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='proc',
            field=models.IntegerField(choices=[('Standard', 'Standard'), ('Expedited', 'Expedited')], default='Standard'),
        ),
    ]
