# Generated by Django 3.1.1 on 2020-11-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20201108_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('arbs', models.IntegerField(choices=[(1, '1'), (3, '3')], default=3)),
                ('proc', models.CharField(choices=[('Standard', 'Standard'), ('Expedited', 'Expedited')], default='Standard', max_length=16)),
                ('ai', models.ManyToManyField(to='calc.ArbInst')),
            ],
        ),
        migrations.AlterField(
            model_name='cost',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='calc.userreq'),
        ),
        migrations.DeleteModel(
            name='UserRequest',
        ),
    ]
