# Generated by Django 3.1.1 on 2020-11-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_auto_20201108_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReq',
            new_name='UserRequest',
        ),
    ]
