# Generated by Django 3.1.1 on 2020-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='ea',
            field=models.IntegerField(choices=[(1, '1'), (3, '3')], default=3),
        ),
    ]
