# Generated by Django 3.1.1 on 2020-11-30 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_auto_20201130_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='ea',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=8),
        ),
    ]
