# Generated by Django 3.1.1 on 2020-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_auto_20201130_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='comment3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='em_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='max_arbs_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='med_arbs_fee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='min_arbs_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
