# Generated by Django 3.1.1 on 2020-12-02 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_auto_20201202_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='comment3',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='max_arbs_fee',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='med_arbs_fee',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='min_arbs_fee',
        ),
        migrations.CreateModel(
            name='CostRu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_fee', models.FloatField(blank=True, null=True)),
                ('arb_fee', models.FloatField(blank=True, null=True)),
                ('arbs_fee', models.FloatField(blank=True, null=True)),
                ('admin_fee', models.FloatField(blank=True, null=True)),
                ('comment0', models.TextField(blank=True, null=True)),
                ('comment1', models.TextField(blank=True, null=True)),
                ('comment2', models.TextField(blank=True, null=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.arbinstru')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='calc.userrequestru')),
            ],
        ),
    ]
