# Generated by Django 3.1.1 on 2020-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_auto_20201202_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequestru',
            name='proc',
            field=models.CharField(choices=[('Стандартная', 'Стандартная'), ('Ускоренная', 'Ускоренная')], default='Стандартная', max_length=16),
        ),
        migrations.AlterField(
            model_name='userrequestru',
            name='type',
            field=models.CharField(choices=[('Внутренний', 'Внутренний'), ('Корпоративный', 'Корпоративный')], default='Внутренний', max_length=16),
        ),
    ]
